name: quiz-gen
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.6.0
  - anyio=4.3.0
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - colorama=0.4.6
  - distro=1.9.0
  - exceptiongroup=1.2.0
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - idna=3.7
  - iniconfig=2.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=17.0.6
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libsqlite=3.45.3
  - libzlib=1.2.13
  - llvm-openmp=18.1.5
  - ncurses=6.4
  - numpy=1.26.4
  - openai=1.29.0
  - openssl=3.3.0
  - packaging=24.0
  - pip=24.0
  - pluggy=1.5.0
  - pydantic=2.7.1
  - pydantic-core=2.18.2
  - pytest=8.2.0
  - python=3.10.13
  - python_abi=3.10
  - readline=8.2
  - setuptools=69.5.1
  - sniffio=1.3.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tomli=2.0.1
  - tqdm=4.66.4
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - charset-normalizer==3.3.2
      - requests==2.31.0
      - urllib3==2.2.1
prefix: /opt/miniconda3/envs/quiz-gen
