name: quiz-gen
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.6.0
  - anyio=4.3.0
  - appnope=0.1.4
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - certifi=2024.6.2
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.8.1
  - decorator=5.1.1
  - distro=1.9.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - idna=3.7
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - iniconfig=2.0.0
  - ipykernel=6.29.4
  - ipython=8.25.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - krb5=1.21.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=17.0.6
  - libedit=3.1.20191231
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libzlib=1.2.13
  - llvm-openmp=18.1.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - openai=1.29.0
  - openssl=3.3.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - prompt-toolkit=3.0.47
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pydantic=2.7.1
  - pydantic-core=2.18.2
  - pygments=2.18.0
  - pytest=8.2.0
  - python=3.10.13
  - python-dateutil=2.9.0
  - python_abi=3.10
  - pyzmq=26.0.3
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sniffio=1.3.1
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - charset-normalizer==3.3.2
      - frozenlist==1.4.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.2.3
      - langchain-core==0.2.5
      - langchain-openai==0.1.8
      - langchain-text-splitters==0.2.1
      - langsmith==0.1.77
      - multidict==6.0.5
      - orjson==3.10.4
      - packaging==23.2
      - pyyaml==6.0.1
      - regex==2024.5.15
      - requests==2.31.0
      - sqlalchemy==2.0.30
      - tenacity==8.3.0
      - tiktoken==0.7.0
      - urllib3==2.2.1
      - yarl==1.9.4
prefix: /opt/miniconda3/envs/quiz-gen
